### ISSUE TITLE
Request to add additional "description" meta tag

### ISSUE THREAD

**Issue by nowlena** [phpBBSEO/meta#4]
I would suggest that the "description" meta tag content is duplicated and rendered again under the "og:description" tag.

**Comment by dcz** [comment]
I will make this optional.

Do you know of any other og tag that could have some interest ?

**Comment by nowlena** [comment]
ADDITIONS TO CORE.PHP:
lang --> meta property="og:locale" content="..."
title --> meta property="og:title" content="..."

ADDITIONS TO HEADER IN GENERAL:
site name ( put Forum's name as content ) --> meta property="og:site_name" content="..."
url ( put canonical URL as content )--> meta property="og:url" content="..."

**Comment by dcz** [comment]
here something usable : https://github.com/phpBBSEO/meta/issues/5
It's first draft, I think I will add some option in acp to add fb user id. Could also look up post for images.
https://developers.facebook.com/docs/sharing/best-practices

**Comment by nowlena** [comment]
That's a good idea... in the new style I'm working on I put:

Facebook url --> meta property="article:publisher" content="..."

Google+ url --> link rel="publisher" href="..."

Twitter handle --> meta name="twitter:site" content="@..." and meta name="twitter:creator" content="@..."

Site name ( for 3rd time ) --> meta name="twitter:domain" content="..."

**Comment by dcz** [comment]
I just added image, tag, using first image in first post if any. I also added acp option to activate in usu extended with fb app_id.

I'm not sure about twitter, because he is using og if present and og are already pretty redundant with meta tags.

Could be another request though.

I think I'm close to merge this one into master.
